### ISSUE TITLE
caching GDevelop downloads

### ISSUE THREAD

**Issue by HiranChaudhuri** [arthuro555/gdexporter#6]
I have a CI/CD pipeline that automatically builds GDevelop based games. For this I placed the gdexporter in a docker container, and whenever it is run I get output similar to the below:

```
📓 No config file found!
⌛ Loading plugins...
⌛ Loading GDCore...
🕗 Getting latest release tag...
❌ The GDevelop version was not found, downloading it!
🕗 Starting download of GDevelop Runtime 'v5.0.0-beta119'...
🕗 Starting download of GDevelop Core...
✅ Done downloading libGD.js
✅ Done downloading GDevelop Runtime 'v5.0.0-beta119'
🕗 Extracting GDevelop Runtime 'v5.0.0-beta119'...
✅ Done extracting the GDevelop Runtime
🕗 Compiling Runtime...
✅ Done downloading libGD.wasm
✅ Runtime built in 993ms
✅ Successfully downloaded GDevelop version 'v5.0.0-beta119'
⌛ Loading project...
[rest of output]
```

Now compiling 7 projects in a row will lead to GDevelop being downloaded 7 times before each of the projects is getting processed. So I am thinking of two ways to improve on that:

### 1) baking GDevelop version into the gdexporter image
For this I'd need to trigger gdexporter during image creation, when no project is available.
Which command could I use for that? Or would it be better to provide a dummy project?

### 2) storing cached downloads outside of my gdexporter container
Which directory is actually used to store and find GDevelop versions?

**Comment by arthuro555** [comment]
The GDevelop files are stored into the node_modules folder, alongside gdexporter's code. If you cache that folder (which is generally recommended to make `npm install` runs faster) you should be caching the GDevelop version runtime downloads too.

**Comment by HiranChaudhuri** [comment]
I was taking a closer look at the directory /usr/local/lib/node_modules, but both before and after the gdexporter run it contains only
- corepack
- gdexporter
- npm

I do not yet see the exact location that should be cached. What lookup is behind this message?
...
❌ The GDevelop version was not found, downloading it!
...

**Comment by HiranChaudhuri** [comment]
To be more precise:
After installing gdexporter the directory /usr/local/lib/node_modules/gdexporter/node_modules/gdcore-tools/src/Versions does not exist, but after having compiled one project it exists. I will set a docker volume mount here.
